<a href="https://colab.research.google.com/github/zahra-debug/CODECRAFT_WD_01/blob/main/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY

Installation of numpy


In [ ]:
!pip install numpy


In [ ]:
#import the library
import numpy as np

ARRAYS
array is a grid of value and it contain info about raw data how to locate an element,and how to interpret an element.

In [ ]:
#diff btw array and list
list = [1,2,3,4,5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
array= np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#create a 1D array from list
arr1 = np.array([1,2,3,4,5,6])
print("1D Array:",arr1)

1D Array: [1 2 3 4 5 6]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
#2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:",arr2)

2D Array: [[1 2 3]
 [4 5 6]]


In [ ]:
#3D Array
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("3D Array:",arr3)

3D Array: [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

ARRAY ATTRIBUTES
this covers the ndim,shape,size and dtype attributes of array

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:", arr2)
arr2.ndim  #tell the dim like 1d,2d


2D Array: [[1 2 3]
 [4 5 6]]


2

In [ ]:
arr3.shape

(1, 3, 3)

In [ ]:
arr3.size

9

In [ ]:
arr3.dtype

dtype('int64')

In [ ]:
#Arrays are typically "homogenous", meaning that they contain lelments of only one "data type.
#The data type is recorded in the dtype atrribute.

How to create a basic array
This section covers np.zeros().np.ones(),np.empty(),np.arrange(),np.linspace().

In [ ]:
a= np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [ ]:
#create an array of zeros(shape = 3*3)
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#create an array of zeros(shape = ((2*4))
zeros=np.zeros((2,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#create an empty array of 2 elements
np.empty(2)

array([8.26670048e+114, 7.92395544e-177])

In [ ]:
a=np.empty(2)
a

array([8.26670048e+114, 7.92395544e-177])

In [ ]:
#arrange
np.arange(5)


array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [ ]:
a

array([8.26670048e+114, 7.92395544e-177])

In [ ]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
#reshape array
b=a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
x= np.reshape(a,(1,4),order=)


ValueError: cannot reshape array of size 6 into shape (1,4)

In [ ]:
#create a range of values(start,end,step)
range_arr = np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [ ]:
#create equally spaced values(start,end,no_of_values)
linspace=np.linspace(0,10,5)
linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x= np.ones(3,dtype=np.int64)
x

array([1, 1, 1])

ADDING,REMOVING,SORTING ELEMENTS

In [ ]:
arr=np.array([2,1,5,6,4,6,8])
np.sort(arr)

array([1, 2, 4, 5, 6, 6, 8])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

INDEXING AND SLICING
You can index and slice numpy arrays in same ways you can slice python lists.

In [ ]:
data=np.array([1,2,3,5,8,9])
data[1]

np.int64(2)

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3, 5, 8, 9])

In [ ]:
data[-2:]

array([8, 9])

In [ ]:
#indexing with condition
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a<5])

[1 2 3 4]


In [ ]:
five_up= (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
five_up =  (a>5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


HOW TO CREATE AN ARRAY FROM EXISTING DATA
THIS includes slicing and indexing,np.vstack(),np.hstack().np.hsplit(),view(),copy()

In [ ]:
arr.view()

array([2, 1, 5, 6, 4, 6, 8])

In [ ]:
a1= np.array([[1,1],
             [2,2]])
a2 =np.array([[3,3],
             [4,4]])

np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
x= np.arange(1,25).reshape(2,12)

x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
#if y want to split this array into equally shaped
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
#if u want to split your array after 3rd or  4th col,you would run
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
x= x[0,:]
x

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
#copy


Basic array oepprations use of random function

In [ ]:
a=np.random.rand(4)
a

array([0.3860435 , 0.31617428, 0.18051475, 0.65721813])

In [ ]:
b=np.random.rand(5)
b

array([0.34695961, 0.74288195, 0.05511196, 0.70507987, 0.82579206])

In [ ]:
import numpy as np
#gENERATE 5*2 array with rand int grom 0 to 9
data=np.random.randint(0,10,size=(5,2))
data

array([[8, 6],
       [9, 5],
       [0, 0],
       [3, 7],
       [2, 5]])

In [ ]:
c= np.add(a,b)
c

array([ 6,  8, 10, 12])

In [ ]:
c=a+b
c

array([ 6,  8, 10, 12])

In [ ]:
data=np.array([1.0,2.0])
data*1.6

array([1.6, 3.2])

In [ ]:
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
sum=np.sum([arr1,arr2])
sum

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#iterating
# it is used to beak each element
for i in arr1:
   print(i)

1
2
3
4
5
6


In [ ]:
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
for i in arr2:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
#use of nditer()
for x in np.nditer(arr2):
  print(x)

1
2
3
4
5
6


In [ ]:
#use of ndenominator
for i,d in np.ndenumerate(arr2):
  print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
h=np.ravel(arr3)
h

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#linear algebra
Data is store in vector,matrix,and tensor,it deals with algebra and matthematics.

In [ ]:
#transpose
arr

array([2, 1, 5, 6, 4, 6, 8])

In [ ]:
x=arr.T
x

array([2, 1, 5, 6, 4, 6, 8])

In [ ]:
x=arr

In [ ]:
a=np.matrix([1,2,3,4,5,6,7,8])

In [ ]:
x=a.T
x

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [ ]:
b=a.copy()
b

matrix([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
b.shape

(1, 8)

In [ ]:
c = np.dot(arr1,arr1)  #willl get answer in scaler
c

np.int64(91)

In [ ]:
d = np.diag(arr)
d

array([[2, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 8]])

In [ ]:
s=np.identity(6)
s

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
#solving question by cramers rule
x=np.linalg.solve(a,b)
x

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
import numpy as np
#define a coeffecient matrix (A) and right hand side vector(b)
A= np.array([[3,1],[1,2]]) #2*2 matrix
b=np.array([9,8])  #2-eleement vector

#Solve the linear system :A*x = b
x =np.linalg.solve(A,b)  #x holds the solution of system

print("Solution of A*x=b:",x)

Solution of A*x=b: [2. 3.]


In [ ]:

#define a square matrix
matrix=np.array([[4,2],[2,6]])
matrix_inv=np.linalg.inv(matrix)

print("Matrix inverse:\n",matrix_inv)

Matrix inverse:
 [[ 0.3 -0.1]
 [-0.1  0.2]]
